### ISSUE TITLE
Few questions about PR

### ISSUE THREAD

**Issue by fmckeogh** [althonos/pruefung#2]
Hello!

I’m working on a PR to add crc8, crc16 and crc64 algorithms and have a few questions.

- Running `cargo fmt` resulted in a whole lot of changes. Would you prefer a second PR for that?
- Would you be OK with adding a feature for choosing between precalculated and live generated tables? IE if a user is memory constrained then precalculated makes sense, if a user is space constrained then live makes sense
- I plan on making the default be to use ANSI definitions of each algorithms constants, and allow both the selection of different standards *and* the use of custom polynomials, start values and final values. I’m not sure if both are necessary, as someone needing to use a non-ANSI version likely knows what constants they need.

Thanks!

**Comment by althonos** [comment]
Hello Ferdia !

First of all, thanks for giving this project some attention, I have not been very active on it for the past year. Concerning your questions:

> Running cargo fmt resulted in a whole lot of changes. Would you prefer a second PR for that?

Yes it would be great, although I can also run it on the current `master` branch, and then you'd only have to rebase against it (which should result in a smaller diff).

> Would you be OK with adding a feature for choosing between precalculated and live generated tables? IE if a user is memory constrained then precalculated makes sense, if a user is space constrained then live makes sense

Absolutely, this makes complete sense.

> I plan on making the default be to use ANSI definitions of each algorithms constants, and allow both the selection of different standards and the use of custom polynomials, start values and final values. I’m not sure if both are necessary, as someone needing to use a non-ANSI version likely knows what constants they need.

Ok, great ! I guess doing both would be interesting for optimisation purpose, since by adding specific standards you could still define a lookup table quite easily, whereas a generic CRC could not (well, you could precalculate the table with a macro at compile-time, but that's some extra work :wink:)

Anyway, I'll try to be reactive since it's always great to have contributors !

**Comment by fmckeogh** [comment]
That would be really great if you could do that, it will make code review easier at the very least. :)

I hadn't thought of using a macro, but that really seems like the best solution so I will start work.

I just wanted to say how much I appreciated this project when working on embedded, it's really great to be able to use RustCrypto style/traits! :D

**Comment by althonos** [comment]
Done !

**Comment by fmckeogh** [comment]
CRC8, 16 and 64 are all working and have tests, and I’ve made good progress on the two methods for lookup table generation. Would you prefer these as separate PRs (once finished)?

**Comment by althonos** [comment]
@chocol4te: Sorry I'm only answering this now ! Actually having two different PRs would be great, but if you already have a git history that's hard to uncouple then I'd be fine with only one.
